# Processing of a resting-state EEG dataset for sleep deprivation

Bad channels are interpolated

## PRE PROCESSING

#### The intention is to provide epochs(4 seconds) to the machine and try predicting if the case is sleep deprivation or normal sleep.

In [1]:
from matplotlib import pyplot as plt
import os
import pandas as pd
import numpy as np
from scipy import signal
import mne
import mne_icalabel
from mne.preprocessing import ICA
from autoreject import Ransac  
from mne_icalabel import label_components
%matplotlib inline

In [2]:
# lists to collect data
X_list = []
y_list = []
data_NS_list =[]
data_SD_list =[]

In [3]:
n_epochs = 0
for i in range(1, 72):
    if i == 28 or i== 1 or i== 44 or i==39 or i==43 or i in [7,8,11,13,18,24,29,31,35,36,37,38,40,47,48,50,54,58,59,63,67,70,71]: #46 participants with complete data
        continue  # Skip participants due to missing data
    for j in range(1, 3):
        
        #Define file path
        file_path = f'D:\\BCI\\TASKS\\Task-8\\ds004902_data\\sub-{i:02d}\\ses-{j}\\eeg\\sub-{i:02d}_ses-{j}_task-eyesopen_eeg.set'#The d indicates that the value is a decimal integer, while the 02 specifies that the output should be padded with leading zeros if necessary to reach a width of two characters.
        epochs_file = f'D:\\BCI\\TASKS\\Task-8\\processed_epochs_60\\sub-{i:02d}_ses-{j}_epochs.fif'  # Path to save/load processed epochs
        
        
        if os.path.exists(epochs_file):
            print(f"Loading processed epochs from {epochs_file}")
            epochs = mne.read_epochs(epochs_file, preload=True)
        else:
            print(f"\nProcessing: {file_path}\n")

            #Define EEG channels
            eeg_channels = ["Fp1", "AF3", "AF7", "Fz", "F1", "F3", "F5", "F7","FC1", "FC3", "FC5", "FT7","Cz", "C1", "C3", "C5", "T7","CP1", "CP3", "CP5", "TP7", "TP9","Pz", "P1", "P3", "P5", "P7","PO3", "PO7", "Oz", "O1","Fpz", "Fp2", "AF4", "AF8","F2", "F4", "F6", "F8","FC2", "FC4", "FC6", "FT8","C2", "C4", "C6", "T8","CPz", "CP2", "CP4", "CP6","TP8", "TP10","P2", "P4", "P6", "P8","POz", "PO4", "PO8", "O2"]
            
            #Load EEG data
            raw = mne.io.read_raw_eeglab(file_path, preload=True)
            eeg_raw=raw.pick(mne.pick_channels(raw.info['ch_names'], include=eeg_channels))
            
            #Montage setting
            montage = mne.channels.make_standard_montage('standard_1020')
            eeg_raw.set_montage(montage)

            #Filtering
            eeg_raw.filter(1., 40.)#, fir_design='firwin')

            #Average Referencing
            eeg_raw.set_eeg_reference('average')

            #EPOCHING
            epochs = mne.make_fixed_length_epochs(eeg_raw, duration=60.0, overlap=0.0,preload=True)

            #RANSAC for bad channel detection
            ransac = Ransac(verbose=False, n_jobs=1)
            ransac.fit(epochs)
            epochs.info['bads'].extend(ransac.bad_chs_)   

            #interpolate bad channels
            epochs.interpolate_bads(reset_bads=True)
            
            #ICA for artifact removal
            ica = mne.preprocessing.ICA(n_components=20, method='infomax', fit_params=dict(extended=True), random_state=42, max_iter=1000)
            ica.fit(epochs)

            ic_labels = label_components(epochs, ica, method='iclabel')
            exclude_idx = []
            for idx, label in enumerate(ic_labels["labels"]):
                if label not in ["brain","other","muscle artifact"] and ic_labels["y_pred_proba"][idx] > 0.5:
                    exclude_idx.append(idx)

            ica.apply(epochs,exclude= exclude_idx)           

            # Save processed epochs
            os.makedirs(os.path.dirname(epochs_file), exist_ok=True) #creates the necessary directories for the file path if they don't exist.
            epochs.save(epochs_file, overwrite=True)
            print(f"Saved processed epochs to {epochs_file}")

        if j==1:
            labels = 0
        elif j==2:
            labels = 1
        labels = pd.DataFrame({'label': [labels]*len(epochs)})
        
        # Extract data and labels
        data = epochs.get_data()  # shape: (n_epochs, n_channels, n_times)

        #if (i == 39 or i == 43) and j == 2:
        #    data = signal.decimate(data, 10, axis=2) # Downsample by a factor of 10 to match time points.

        epoch_labels = labels['label'].values  
        
        if i <= 71:  
            X_list.append(data)
            y_list.append(epoch_labels)

        if j==1:
            data_NS_list.append(data)
        elif j==2:
            data_SD_list.append(data)

# After the loop, concatenate into arrays
X= np.concatenate(X_list, axis=0)
y = np.concatenate(y_list, axis=0)
data_SD = np.concatenate(data_SD_list, axis=0)
data_NS = np.concatenate(data_NS_list, axis=0)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-02_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-02_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-02_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-02_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-02_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-02_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-03_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-03_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-03_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-03_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-03_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-03_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-04_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-04_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-04_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-04_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-04_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-04_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-05_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-05_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-05_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-05_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-05_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-05_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-06_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-06_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-06_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-06_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-06_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-06_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-09_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-09_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-09_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-09_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-09_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-09_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-10_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-10_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-10_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-10_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-10_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-10_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-12_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-12_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-12_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-12_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-12_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-12_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-14_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-14_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-14_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-14_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-14_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-14_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-15_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-15_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-15_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-15_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-15_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-15_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-16_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-16_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-16_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-16_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-16_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-16_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-17_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-17_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-17_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-17_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-17_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-17_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-19_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-19_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-19_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-19_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-19_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-19_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-20_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-20_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-20_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-20_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-20_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-20_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-21_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-21_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-21_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-21_ses-2_epochs.fif ...

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-21_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)
C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-21_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-22_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-22_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-22_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-22_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-22_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-22_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-23_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-23_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-23_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-23_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-23_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-23_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-25_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-25_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-25_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-25_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-25_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-25_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-26_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-26_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-26_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-26_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-26_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-26_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-27_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-27_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-27_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-27_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-27_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-27_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-30_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-30_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-30_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-30_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-30_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-30_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-32_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-32_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-32_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-32_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-32_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-32_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-33_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-33_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-33_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-33_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-33_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-33_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-34_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-34_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-34_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-34_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-34_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-34_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-41_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-41_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-41_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-41_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-41_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-41_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-42_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-42_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-42_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-42_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-42_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-42_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-45_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-45_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-45_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-45_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-45_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-45_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-46_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-46_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-46_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-46_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-46_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-46_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

4 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-49_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-49_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-49_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-49_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-49_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-49_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-51_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-51_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-51_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-51_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-51_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
4 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-51_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-52_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-52_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-52_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-52_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-52_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-52_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
6 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-53_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-53_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-53_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-53_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-53_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-53_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-55_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-55_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-55_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-55_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-55_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-55_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-56_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-56_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-56_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-56_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-56_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-56_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-57_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-57_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-57_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-57_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-57_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
4 matching events found

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-57_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-60_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-60_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-60_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
4 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-60_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-60_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-60_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-61_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-61_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-61_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-61_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-61_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-61_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-62_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-62_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-62_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-62_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-62_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata
4 matching events found
No baseline correction applied
0 projection items activated

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-62_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-64_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-64_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-64_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-64_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-64_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-64_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-65_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-65_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-65_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-65_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-65_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available
Not setting metadata

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-65_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

3 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-66_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-66_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-66_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-66_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-66_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-66_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-68_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-68_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-68_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-68_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-68_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-68_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-69_ses-1_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-69_ses-1_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-69_ses-1_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated
Loading processed epochs from D:\BCI\TASKS\Task-8\processed_epochs_60\sub-69_ses-2_epochs.fif
Reading D:\BCI\TASKS\Task-8\processed_epochs_60\sub-69_ses-2_epochs.fif ...
    Found the data of interest:
        t =       0.00 ...   59998.00 ms
        0 CTF compensation matrices available

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3940900364.py:14: RuntimeWarning: This filename (D:\BCI\TASKS\Task-8\processed_epochs_60\sub-69_ses-2_epochs.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs(epochs_file, preload=True)

Not setting metadata
5 matching events found
No baseline correction applied
0 projection items activated

In [4]:
print(X.shape)
print(y.shape)
print(data_SD.shape)
print(data_NS.shape)
print(X)
print(y)

(424, 61, 30000)
(424,)
(210, 61, 30000)
(214, 61, 30000)
[[[-1.86939514e-09 -1.33587992e-06 -2.67785286e-06 ...  3.39845633e-06
    2.90296911e-06  2.38385891e-06]
  [-1.94064725e-09  1.98257356e-07  1.31205871e-07 ...  6.59083508e-06
    6.43760393e-06  6.10524176e-06]
  [-1.08360790e-09 -6.29877148e-07 -1.39925456e-06 ...  2.80599474e-06
    2.63128828e-06  2.36371660e-06]
  ...
  [ 4.23254502e-10  1.06595909e-06  2.29082608e-06 ...  1.41882562e-06
    2.76843046e-06  3.73536276e-06]
  [ 4.71726466e-10  2.87471890e-07  8.53711305e-07 ...  1.00523967e-05
    1.02179270e-05  9.79988763e-06]
  [ 5.23308931e-10  1.85923862e-06  3.72308849e-06 ...  3.99468016e-06
    6.16059874e-06  7.70940350e-06]]

 [[ 1.86271786e-06  1.33896160e-06  7.96520708e-07 ... -9.06401095e-07
   -8.24688671e-08  6.52927635e-07]
  [ 5.61213015e-06  4.99401473e-06  4.29776095e-06 ... -4.90488957e-06
   -4.45498608e-06 -4.03521632e-06]
  [ 2.02848935e-06  1.65482366e-06  1.27060425e-06 ... -2.20463204e-06
   -1.55794334e-06 -9.74806068e-07]
  ...
  [ 4.19223308e-06  4.13747119e-06  3.68614935e-06 ...  7.63717077e-06
    7.04470728e-06  6.24437474e-06]
  [ 8.77088735e-06  7.22569988e-06  5.35655306e-06 ...  9.95424554e-06
    9.89843271e-06  9.70019433e-06]
  [ 8.34820936e-06  8.02783201e-06  6.93992184e-06 ...  1.09335060e-05
    1.06217813e-05  1.03456850e-05]]

 [[ 1.23076951e-06  1.60203826e-06  1.74242174e-06 ... -2.99661683e-06
   -2.73781204e-06 -2.31143426e-06]
  [-3.66883229e-06 -3.37404274e-06 -3.16372823e-06 ... -3.41100483e-07
   -7.30416400e-08  1.68950036e-07]
  [-5.07733463e-07 -1.98011428e-07 -6.69971926e-08 ...  2.97039329e-07
    2.95340388e-07  1.68277829e-07]
  ...
  [ 5.34054993e-06  4.45068930e-06  3.67688941e-06 ...  1.48446262e-06
    9.16495261e-07 -9.51184181e-08]
  [ 9.43184278e-06  9.15338514e-06  8.89765833e-06 ...  3.17082810e-06
    3.33191084e-06  3.22077703e-06]
  [ 1.03423214e-05  1.07976589e-05  1.17800140e-05 ...  6.95045756e-06
    6.38421486e-06  5.52298258e-06]]

 ...

 [[ 3.12431215e-07  3.19934200e-06  5.34190224e-06 ...  7.24782227e-06
    7.67490623e-06  8.06384752e-06]
  [-5.79499005e-06 -6.27541350e-06 -6.71037005e-06 ... -3.13086414e-06
   -3.14322399e-06 -3.23542999e-06]
  [-7.68074129e-06 -8.91403005e-06 -9.64877317e-06 ...  3.03694534e-06
    2.75486993e-06  2.60076832e-06]
  ...
  [ 1.13783693e-05  1.23156252e-05  1.29132118e-05 ...  2.81899595e-06
    4.95844315e-06  7.24386881e-06]
  [ 1.24813585e-05  1.32811556e-05  1.37652940e-05 ...  2.88859987e-06
    4.23776769e-06  6.04948519e-06]
  [ 7.24010370e-06  8.02220724e-06  8.40031717e-06 ...  1.01190538e-05
    1.39385337e-05  1.77754421e-05]]

 [[ 8.36731336e-06  8.51315687e-06  8.42194650e-06 ... -6.92748736e-06
   -9.76354406e-06 -1.20448360e-05]
  [-3.31192397e-06 -3.31800269e-06 -3.25650119e-06 ...  6.54043101e-06
    6.07886551e-06  4.52547072e-06]
  [ 2.61585998e-06  2.76554679e-06  2.94775819e-06 ... -6.71804283e-06
   -6.61687706e-06 -5.80739783e-06]
  ...
  [ 9.36750219e-06  1.10859337e-05  1.22653818e-05 ...  1.01173913e-06
    7.21821485e-07  8.51992128e-07]
  [ 7.95333050e-06  9.65725706e-06  1.10042152e-05 ... -5.13043307e-06
   -4.47051619e-06 -3.24879431e-06]
  [ 2.07854022e-05  2.24246578e-05  2.25631523e-05 ... -1.21933721e-07
   -2.90976673e-07 -1.56588688e-07]]

 [[-1.33553333e-05 -1.34779100e-05 -1.24568414e-05 ... -2.14549994e-06
   -1.11594820e-06 -6.01363879e-09]
  [ 2.13883209e-06 -7.09521649e-07 -3.59315919e-06 ... -1.82815933e-06
   -9.57963285e-07  3.64879308e-09]
  [-4.47110509e-06 -2.88196825e-06 -1.33378768e-06 ... -1.20150530e-06
   -6.45325778e-07  2.36961692e-08]
  ...
  [ 1.37248540e-06  2.18649291e-06  3.15317940e-06 ...  1.84014189e-06
    9.36210153e-07  4.57838968e-09]
  [-1.66426456e-06  3.91686744e-08  1.62857663e-06 ...  3.92037331e-07
    2.37944602e-07  2.33383802e-09]
  [ 2.67633676e-07  9.58165882e-07  1.88452243e-06 ...  3.73874514e-07
    2.54204362e-07  4.76667097e-09]]]
[0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1
 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0
 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0
 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1
 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0
 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0
 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1
 1 1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0
 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0
 0 0 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0
 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1]

## Balancing the no of epochs

In [5]:
min_length = min(len(data_NS), len(data_SD))
print("Minimum length for balancing:", min_length)
def balance_data(data_array, target_length):
    # If this is the larger array, sample it down
    if len(data_array) > target_length:
        # random_state=42 ensures you get the same 'random' choice every time (reproducible)
        indices = np.random.choice(len(data_array), target_length, replace=False)
        return data_array[indices]
    return data_array

Minimum length for balancing: 210

In [6]:
data_NS = balance_data(data_NS, min_length)
data_SD = balance_data(data_SD, min_length)
print("Balanced data_NS shape:", data_NS.shape)
print("Balanced data_SD shape:", data_SD.shape)

Balanced data_NS shape: (210, 61, 30000)
Balanced data_SD shape: (210, 61, 30000)

In [7]:
#no of epoches obtained
n_epochs = data_NS.shape[0] + data_SD.shape[0]
print("Total number of epochs:", n_epochs)

Total number of epochs: 420

## Band Power Extraction

In [8]:
# Bandpower extraction functions
def bandpower_delta(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    delta_band = (0.5, 4)
    mask = (freqs >= delta_band[0]) & (freqs <= delta_band[1])
    delta_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis)
    return delta_power

def bandpower_theta(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    theta_band = (4, 8)
    mask = (freqs >= theta_band[0]) & (freqs <= theta_band[1])
    theta_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis)
    return theta_power

def bandpower_alpha(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    alpha_band = (8, 13)
    mask = (freqs >= alpha_band[0]) & (freqs <= alpha_band[1])
    alpha_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis)
    return alpha_power  

def bandpower_beta(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    beta_band = (13, 30)
    mask = (freqs >= beta_band[0]) & (freqs <= beta_band[1])
    beta_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis)
    return beta_power       

def bandpower_gamma(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    gamma_band = (30, 40)
    mask = (freqs >= gamma_band[0]) & (freqs <= gamma_band[1])
    gamma_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis)
    return gamma_power

def bandpower_total(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    total_band = (0.5, 40)
    mask = (freqs >= total_band[0]) & (freqs <= total_band[1])
    total_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis)
    return total_power

In [9]:
# Average Bandpower extraction functions
def average_bandpower_delta(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    delta_band = (0.5, 4)
    mask = (freqs >= delta_band[0]) & (freqs <= delta_band[1])
    delta_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis) # dimensions: (n_epochs, n_channels)
    average_delta_bandpower = np.mean(delta_power, axis= -1)  # Average across channels
    return average_delta_bandpower

def average_bandpower_theta(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    theta_band = (4, 8)
    mask = (freqs >= theta_band[0]) & (freqs <= theta_band[1])
    theta_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis)
    average_theta_bandpower = np.mean(theta_power, axis=-1)  # Average across channels
    return average_theta_bandpower

def average_bandpower_alpha(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    alpha_band = (8, 13)
    mask = (freqs >= alpha_band[0]) & (freqs <= alpha_band[1])
    alpha_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis)
    average_alpha_bandpower = np.mean(alpha_power, axis=-1)  # Average across channels
    return average_alpha_bandpower      

def average_bandpower_beta(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    beta_band = (13, 30)
    mask = (freqs >= beta_band[0]) & (freqs <= beta_band[1])
    beta_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis)
    average_beta_bandpower = np.mean(beta_power, axis=-1)  # Average across channels
    return average_beta_bandpower

def average_bandpower_gamma(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    gamma_band = (30, 40)
    mask = (freqs >= gamma_band[0]) & (freqs <= gamma_band[1])
    gamma_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis)
    average_gamma_bandpower = np.mean(gamma_power, axis=-1)  # Average across channels
    return average_gamma_bandpower

def average_bandpower_total(sample_data, fs=500, axis=-1):
    freqs, psd_values = signal.welch(sample_data, fs=fs, axis=axis)
    total_band = (0.5, 40)
    mask = (freqs >= total_band[0]) & (freqs <= total_band[1])
    total_power = np.trapezoid(psd_values[..., mask], freqs[mask], axis=axis)
    average_total_bandpower = np.mean(total_power, axis=-1)  # Average across channels
    return average_total_bandpower

In [10]:
#calculation of delta band powers for both SD and NS data
from tqdm import tqdm_notebook
delta_power_SD_list=[]
for datta in tqdm_notebook(data_SD):
    ith_delta_powers_SD = bandpower_delta(datta, fs=500)
    delta_power_SD_list.append(ith_delta_powers_SD)

delta_power_SD=np.array(delta_power_SD_list)
delta_power_SD.shape

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\133475402.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for datta in tqdm_notebook(data_SD):

  0%|          | 0/210 [00:00<?, ?it/s]

(210, 61)

In [11]:
#calculation of delta band powers for both SD and NS data
from tqdm import tqdm_notebook
delta_power_NS_list=[]
for datta in tqdm_notebook(data_NS):
    ith_delta_powers_NS = bandpower_delta(datta, fs=500, axis=-1)
    delta_power_NS_list.append(ith_delta_powers_NS)

delta_power_NS=np.array(delta_power_NS_list)
delta_power_NS.shape

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3985284175.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for datta in tqdm_notebook(data_NS):

  0%|          | 0/210 [00:00<?, ?it/s]

(210, 61)

In [12]:
#calculation of theta band powers for both SD data
from tqdm import tqdm_notebook
theta_power_SD_list=[]
for datta in tqdm_notebook(data_SD):
    ith_theta_powers_SD = bandpower_theta(datta, fs=500, axis=-1)
    theta_power_SD_list.append(ith_theta_powers_SD)

theta_power_SD=np.array(theta_power_SD_list)
theta_power_SD.shape

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\759687591.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for datta in tqdm_notebook(data_SD):

  0%|          | 0/210 [00:00<?, ?it/s]

(210, 61)

In [13]:
#calculation of theta band powers for both NS data
from tqdm import tqdm_notebook
theta_power_NS_list=[]
for datta in tqdm_notebook(data_NS):
    ith_theta_powers_NS = bandpower_theta(datta, fs=500, axis=-1)
    theta_power_NS_list.append(ith_theta_powers_NS)

theta_power_NS=np.array(theta_power_NS_list)
theta_power_NS.shape

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\2564802599.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for datta in tqdm_notebook(data_NS):

  0%|          | 0/210 [00:00<?, ?it/s]

(210, 61)

In [14]:
#calculation of alpha band powers for both SD data
from tqdm import tqdm_notebook
alpha_power_SD_list=[]
for datta in tqdm_notebook(data_SD):
    ith_alpha_powers_SD = bandpower_alpha(datta, fs=500, axis=-1)
    alpha_power_SD_list.append(ith_alpha_powers_SD)

alpha_power_SD=np.array(alpha_power_SD_list)
alpha_power_SD.shape

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\705825680.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for datta in tqdm_notebook(data_SD):

  0%|          | 0/210 [00:00<?, ?it/s]

(210, 61)

In [15]:
#calculation of alpha band powers for both NS data
from tqdm import tqdm_notebook
alpha_power_NS_list=[]
for datta in tqdm_notebook(data_NS):
    ith_alpha_powers_NS = bandpower_alpha(datta, fs=500, axis=-1)
    alpha_power_NS_list.append(ith_alpha_powers_NS)

alpha_power_NS=np.array(alpha_power_NS_list)
alpha_power_NS.shape

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\1609555356.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for datta in tqdm_notebook(data_NS):

  0%|          | 0/210 [00:00<?, ?it/s]

(210, 61)

In [16]:
#calculation of beta band powers for both SD data
from tqdm import tqdm_notebook
beta_power_SD_list=[]
for datta in tqdm_notebook(data_SD):
    ith_beta_powers_SD = bandpower_beta(datta, fs=500, axis=-1)
    beta_power_SD_list.append(ith_beta_powers_SD)

beta_power_SD=np.array(beta_power_SD_list)
beta_power_SD.shape

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3865207504.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for datta in tqdm_notebook(data_SD):

  0%|          | 0/210 [00:00<?, ?it/s]

(210, 61)

In [17]:
#calculation of beta band powers for NS data
from tqdm import tqdm_notebook
beta_power_NS_list=[]
for datta in tqdm_notebook(data_NS):
    ith_beta_powers_NS = bandpower_beta(datta, fs=500, axis=-1)
    beta_power_NS_list.append(ith_beta_powers_NS)

beta_power_NS=np.array(beta_power_NS_list)
beta_power_NS.shape

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\3158172285.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for datta in tqdm_notebook(data_NS):

  0%|          | 0/210 [00:00<?, ?it/s]

(210, 61)

In [18]:
#calculation of gamma band powers for SD data
from tqdm import tqdm_notebook
gamma_power_SD_list=[]
for datta in tqdm_notebook(data_SD):
    ith_gamma_powers_SD = bandpower_gamma(datta, fs=500, axis=-1)
    gamma_power_SD_list.append(ith_gamma_powers_SD)

gamma_power_SD=np.array(gamma_power_SD_list)
gamma_power_SD.shape

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\204014121.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for datta in tqdm_notebook(data_SD):

  0%|          | 0/210 [00:00<?, ?it/s]

(210, 61)

In [19]:
#calculation of gamma band powers for NS data
from tqdm import tqdm_notebook
gamma_power_NS_list=[]
for datta in tqdm_notebook(data_NS):
    ith_gamma_powers_NS = bandpower_gamma(datta, fs=500, axis=-1)
    gamma_power_NS_list.append(ith_gamma_powers_NS)

gamma_power_NS=np.array(gamma_power_NS_list)
gamma_power_NS.shape

C:\Users\suvan\AppData\Local\Temp\ipykernel_14688\2721333161.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for datta in tqdm_notebook(data_NS):

  0%|          | 0/210 [00:00<?, ?it/s]

(210, 61)

## Absolute Powers

In [20]:
from scipy import stats
from statsmodels.stats.weightstats import ztest

In [21]:
t_stat_delta, p_delta_t = stats.ttest_ind(delta_power_SD, delta_power_NS, equal_var=False)
z_stat_delta, p_delta_z = ztest(delta_power_SD, delta_power_NS, value=0)
print("DELTA: \n","T_stat:\n", t_stat_delta,"\n","P_stat:\n", p_delta_t,"\n Z_stat:\n", z_stat_delta,"\n p_stat:\n", p_delta_z)

import pandas as pd

eeg_channels = ["Fp1", "AF3", "AF7", "Fz", "F1", "F3", "F5", "F7","FC1", "FC3", "FC5", "FT7","Cz", "C1", "C3", "C5", "T7","CP1", "CP3", "CP5", "TP7", "TP9","Pz", "P1", "P3", "P5", "P7","PO3", "PO7", "Oz", "O1","Fpz", "Fp2", "AF4", "AF8","F2", "F4", "F6", "F8","FC2", "FC4", "FC6", "FT8","C2", "C4", "C6", "T8","CPz", "CP2", "CP4", "CP6","TP8", "TP10","P2", "P4", "P6", "P8","POz", "PO4", "PO8", "O2"]
# Create the DataFrame
df_delta = pd.DataFrame({
    'Channel': eeg_channels,
    'T_Stat': t_stat_delta,
    'P_Value': p_delta_t,
    'Significance': np.where(p_delta_t < 0.05, 'Yes', 'No') 
})
print(df_delta['Significance'].value_counts())
# Filter the DataFrame for significant channels
significant_channels = df_delta[df_delta['Significance'] == 'Yes']['Channel'].tolist()

# Print the list of significant channels
print("\nSignificant Channels:")
print(significant_channels)

DELTA:
 T_stat:
 [ 0.40717437  3.75145542 -0.68082492  6.443173    5.74488966  4.30429819
  0.94458015 -2.20689472  5.0966785   3.81682569 -0.10960551 -0.81695783
  4.87370662  3.56629918  0.86168157 -1.55458046 -1.09745587  4.80153134
 -0.53682054  2.38517199  0.85983759  0.9854206   2.16113947  5.25840201
  3.17864823  2.82173405  3.66880429  1.2431775   3.94891583  4.47062735
  3.07666682  0.94437036  0.71504365  4.13051545  0.8439041   6.18236807
  4.85057084  2.99856227  1.83448017  5.59331717  3.30910621  1.02677543
  2.33386475  3.3335244   1.71149292  0.97175768  0.62539914  3.59262953
  3.63483232  0.31907784  0.74563494  0.19921202  2.03035844  1.1783698
  2.01150463  1.96373282  3.4740926   2.8504699   2.28475413  2.57674626
  1.46483013]
 P_stat:
 [6.84107340e-01 2.09474171e-04 4.96412025e-01 4.89500511e-10
 2.39881790e-08 2.16003662e-05 3.45460884e-01 2.82364412e-02
 5.90038925e-07 1.60050585e-04 9.12775437e-01 4.14420103e-01
 1.79478975e-06 4.14365814e-04 3.89607984e-01 1.20881979e-01
 2.73143218e-01 2.38995251e-06 5.91701536e-01 1.75158910e-02
 3.90373238e-01 3.25081189e-01 3.17544734e-02 2.37540595e-07
 1.59391953e-03 5.00438683e-03 2.82622564e-04 2.14518260e-01
 9.47662142e-05 1.02630943e-05 2.24042800e-03 3.45525959e-01
 4.74985603e-01 5.05630206e-05 3.99235402e-01 2.37970867e-09
 2.12579945e-06 2.90933837e-03 6.73466513e-02 4.90198118e-08
 1.04837918e-03 3.05203342e-01 2.02961259e-02 9.47899699e-04
 8.77534166e-02 3.31781524e-01 5.32056260e-01 3.74891040e-04
 3.14671186e-04 7.49829002e-01 4.56309520e-01 8.42194045e-01
 4.30030734e-02 2.39320075e-01 4.49192881e-02 5.02642001e-02
 5.68573557e-04 4.59625199e-03 2.28353767e-02 1.03164355e-02
 1.43738854e-01]
 Z_stat:
 [ 0.40717437  3.75145542 -0.68082492  6.443173    5.74488966  4.30429819
  0.94458015 -2.20689472  5.0966785   3.81682569 -0.10960551 -0.81695783
  4.87370662  3.56629918  0.86168157 -1.55458046 -1.09745587  4.80153134
 -0.53682054  2.38517199  0.85983759  0.9854206   2.16113947  5.25840201
  3.17864823  2.82173405  3.66880429  1.2431775   3.94891583  4.47062735
  3.07666682  0.94437036  0.71504365  4.13051545  0.8439041   6.18236807
  4.85057084  2.99856227  1.83448017  5.59331717  3.30910621  1.02677543
  2.33386475  3.3335244   1.71149292  0.97175768  0.62539914  3.59262953
  3.63483232  0.31907784  0.74563494  0.19921202  2.03035844  1.1783698
  2.01150463  1.96373282  3.4740926   2.8504699   2.28475413  2.57674626
  1.46483013]
 p_stat:
 [6.83879923e-01 1.75811014e-04 4.95982277e-01 1.17001201e-10
 9.19809479e-09 1.67515909e-05 3.44873265e-01 2.73214153e-02
 3.45664622e-07 1.35179600e-04 9.12722239e-01 4.13952530e-01
 1.09523605e-06 3.62058014e-04 3.88862772e-01 1.20046021e-01
 2.72442163e-01 1.57456857e-06 5.91391581e-01 1.70711382e-02
 3.89878575e-01 3.24417514e-01 3.06845674e-02 1.45312585e-07
 1.47963539e-03 4.77647690e-03 2.43687533e-04 2.13802434e-01
 7.85059462e-05 7.79904885e-06 2.09329132e-03 3.44980423e-01
 4.74582069e-01 3.61950762e-05 3.98722994e-01 6.31470805e-10
 1.23106657e-06 2.71256720e-03 6.65827488e-02 2.22771789e-08
 9.35943259e-04 3.04526224e-01 1.96028053e-02 8.57531484e-04
 8.69901575e-02 3.31171116e-01 5.31709124e-01 3.27357840e-04
 2.78161494e-04 7.49667488e-01 4.55887969e-01 8.42096900e-01
 4.23201178e-02 2.38649210e-01 4.42721822e-02 4.95610845e-02
 5.12584096e-04 4.36546824e-03 2.23272489e-02 9.97351332e-03
 1.42967270e-01]
Significance
Yes    35
No     26
Name: count, dtype: int64

Significant Channels:
['AF3', 'Fz', 'F1', 'F3', 'F7', 'FC1', 'FC3', 'Cz', 'C1', 'CP1', 'CP5', 'Pz', 'P1', 'P3', 'P5', 'P7', 'PO7', 'Oz', 'O1', 'AF4', 'F2', 'F4', 'F6', 'FC2', 'FC4', 'FT8', 'C2', 'CPz', 'CP2', 'TP10', 'P4', 'P8', 'POz', 'PO4', 'PO8']

In [22]:
df_delta.to_excel('t-test_delta.xlsx')
df_delta

   Channel    T_Stat       P_Value Significance
0      Fp1  0.407174  6.841073e-01           No
1      AF3  3.751455  2.094742e-04          Yes
2      AF7 -0.680825  4.964120e-01           No
3       Fz  6.443173  4.895005e-10          Yes
4       F1  5.744890  2.398818e-08          Yes
..     ...       ...           ...          ...
56      P8  3.474093  5.685736e-04          Yes
57     POz  2.850470  4.596252e-03          Yes
58     PO4  2.284754  2.283538e-02          Yes
59     PO8  2.576746  1.031644e-02          Yes
60      O2  1.464830  1.437389e-01           No

[61 rows x 4 columns]

In [23]:
t_stat_theta, p_theta_t = stats.ttest_ind(theta_power_SD, theta_power_NS, equal_var=False)
z_stat_theta, p_theta_z = ztest(theta_power_SD, theta_power_NS, value=0)
print("THETA: \n","T_stat:\n", t_stat_theta,"\n","P_stat:\n", p_theta_t,"\n Z_stat:\n", z_stat_theta,"\n p_stat:\n", p_theta_z)

eeg_channels = ["Fp1", "AF3", "AF7", "Fz", "F1", "F3", "F5", "F7","FC1", "FC3", "FC5", "FT7","Cz", "C1", "C3", "C5", "T7","CP1", "CP3", "CP5", "TP7", "TP9","Pz", "P1", "P3", "P5", "P7","PO3", "PO7", "Oz", "O1","Fpz", "Fp2", "AF4", "AF8","F2", "F4", "F6", "F8","FC2", "FC4", "FC6", "FT8","C2", "C4", "C6", "T8","CPz", "CP2", "CP4", "CP6","TP8", "TP10","P2", "P4", "P6", "P8","POz", "PO4", "PO8", "O2"]
# Create the DataFrame
df_theta = pd.DataFrame({
    'Channel': eeg_channels,
    'T_Stat': t_stat_theta,
    'P_Value': p_theta_t,
    'Significance': np.where(p_theta_t < 0.05, 'Yes', 'No') 
})
print(df_theta['Significance'].value_counts())
# Filter the DataFrame for significant channels
significant_channels = df_theta[df_theta['Significance'] == 'Yes']['Channel'].tolist()

# Print the list of significant channels
print("\nSignificant Channels:")
print(significant_channels)

THETA:
 T_stat:
 [ 2.07660534  3.31515867  1.32362507  3.63519231  3.90831332  3.16327114
  2.35019376  0.90633715  4.40885856  2.77612717  1.04152987  0.44050497
  4.93661376  2.99072564  0.29006546  0.38942561  0.9006811   1.79045504
 -0.09889851  0.93036353  2.04420358  4.40448152  2.21910853  2.6743503
  1.74528174  1.68927181  2.29637164  1.44219466  3.21146243  4.17280843
  3.91711434  2.66227317  2.70046903  2.761717    3.52917836  4.4452439
  3.35350137  3.16650721  3.007419    4.36758198  2.71053914  2.23316711
  3.68290663  3.19425311  0.84105898  1.50691007  3.47978949  2.86972174
  2.06141906  0.59391131  1.13014598  2.39972176  3.69676405  0.22347535
  0.58883442  0.39435205  2.33454193  1.39664657  0.59681058  2.01358779
  1.01349287]
 P_stat:
 [3.84497060e-02 1.02577008e-03 1.86351631e-01 3.30954895e-04
 1.14123032e-04 1.68787135e-03 1.92512542e-02 3.65313227e-01
 1.33899427e-05 5.75277094e-03 2.98262514e-01 6.59807116e-01
 1.20822453e-06 2.95090046e-03 7.71910672e-01 6.97161701e-01
 3.68278493e-01 7.41050458e-02 9.21267223e-01 3.52739871e-01
 4.15669245e-02 1.43143401e-05 2.70301109e-02 7.78403011e-03
 8.16718533e-02 9.19130553e-02 2.21539201e-02 1.50038569e-01
 1.42883836e-03 3.67986254e-05 1.05788343e-04 8.11666181e-03
 7.21189054e-03 6.22917951e-03 4.63677243e-04 1.27553997e-05
 9.21983079e-04 1.65743507e-03 2.93070106e-03 1.60281764e-05
 6.99855772e-03 2.60789843e-02 2.68332458e-04 1.51099773e-03
 4.00807238e-01 1.32613379e-01 5.74828736e-04 4.32353831e-03
 3.98872133e-02 5.52893082e-01 2.59063689e-01 1.68521159e-02
 2.57612100e-04 8.23286070e-01 5.56297350e-01 6.93571283e-01
 2.00418818e-02 1.63262996e-01 5.50957382e-01 4.46937352e-02
 3.11439600e-01]
 Z_stat:
 [ 2.07660534  3.31515867  1.32362507  3.63519231  3.90831332  3.16327114
  2.35019376  0.90633715  4.40885856  2.77612717  1.04152987  0.44050497
  4.93661376  2.99072564  0.29006546  0.38942561  0.9006811   1.79045504
 -0.09889851  0.93036353  2.04420358  4.40448152  2.21910853  2.6743503
  1.74528174  1.68927181  2.29637164  1.44219466  3.21146243  4.17280843
  3.91711434  2.66227317  2.70046903  2.761717    3.52917836  4.4452439
  3.35350137  3.16650721  3.007419    4.36758198  2.71053914  2.23316711
  3.68290663  3.19425311  0.84105898  1.50691007  3.47978949  2.86972174
  2.06141906  0.59391131  1.13014598  2.39972176  3.69676405  0.22347535
  0.58883442  0.39435205  2.33454193  1.39664657  0.59681058  2.01358779
  1.01349287]
 p_stat:
 [3.78379992e-02 9.15911197e-04 1.85627595e-01 2.77773346e-04
 9.29427232e-05 1.56006961e-03 1.87636406e-02 3.64757429e-01
 1.03916863e-05 5.50106868e-03 2.97629699e-01 6.59571412e-01
 7.94906794e-07 2.78315427e-03 7.71766158e-01 6.96961333e-01
 3.67757902e-01 7.33807888e-02 9.21218853e-01 3.52182893e-01
 4.09334394e-02 1.06037179e-05 2.64793420e-02 7.48741968e-03
 8.09358387e-02 9.11673534e-02 2.16546413e-02 1.49247466e-01
 1.32061237e-03 3.00867902e-05 8.96152488e-05 7.76148606e-03
 6.92417827e-03 5.74982926e-03 4.16852078e-04 8.77922083e-06
 7.97960195e-04 1.54281523e-03 2.63476331e-03 1.25629644e-05
 6.71739198e-03 2.55379266e-02 2.30589631e-04 1.40193144e-03
 4.00314895e-01 1.31833710e-01 5.01807900e-04 4.10833160e-03
 3.92630779e-02 5.52571431e-01 2.58414718e-01 1.64075383e-02
 2.18365124e-04 8.23165569e-01 5.55972354e-01 6.93321141e-01
 1.95673631e-02 1.62519878e-01 5.50633855e-01 4.40528298e-02
 3.10824802e-01]
Significance
Yes    38
No     23
Name: count, dtype: int64

Significant Channels:
['Fp1', 'AF3', 'Fz', 'F1', 'F3', 'F5', 'FC1', 'FC3', 'Cz', 'C1', 'TP7', 'TP9', 'Pz', 'P1', 'P7', 'PO7', 'Oz', 'O1', 'Fpz', 'Fp2', 'AF4', 'AF8', 'F2', 'F4', 'F6', 'F8', 'FC2', 'FC4', 'FC6', 'FT8', 'C2', 'T8', 'CPz', 'CP2', 'TP8', 'TP10', 'P8', 'PO8']

In [24]:
df_theta.to_excel('t-test_theta.xlsx')
df_theta

   Channel    T_Stat   P_Value Significance
0      Fp1  2.076605  0.038450          Yes
1      AF3  3.315159  0.001026          Yes
2      AF7  1.323625  0.186352           No
3       Fz  3.635192  0.000331          Yes
4       F1  3.908313  0.000114          Yes
..     ...       ...       ...          ...
56      P8  2.334542  0.020042          Yes
57     POz  1.396647  0.163263           No
58     PO4  0.596811  0.550957           No
59     PO8  2.013588  0.044694          Yes
60      O2  1.013493  0.311440           No

[61 rows x 4 columns]

In [25]:
t_stat_alpha, p_alpha_t = stats.ttest_ind(alpha_power_SD, alpha_power_NS, equal_var=False)
z_stat_alpha, p_alpha_z = ztest(alpha_power_SD, alpha_power_NS, value=0)
print("ALPHA: \n","T_stat:\n", t_stat_alpha,"\n","P_stat:\n", p_alpha_t,"\n Z_stat:\n", z_stat_alpha,"\n p_stat:\n", p_alpha_z)
# Create the DataFrame
df_alpha = pd.DataFrame({
    'Channel': eeg_channels,
    'T_Stat': t_stat_alpha,
    'P_Value': p_alpha_t,
    'Significance': np.where(p_alpha_t < 0.05, 'Yes', 'No') 
})
print(df_alpha['Significance'].value_counts())
# Filter the DataFrame for significant channels
significant_channels = df_alpha[df_alpha['Significance'] == 'Yes']['Channel'].tolist()

# Print the list of significant channels
print("\nSignificant Channels:")
print(significant_channels)

ALPHA:
 T_stat:
 [-0.89087872 -1.24008569 -1.02150847 -1.48808433 -1.43540933 -1.61922721
 -1.18570231 -1.86632461 -1.9848942  -2.30273753 -2.19329417 -1.70184522
 -1.96760191 -3.15524172 -3.87507898 -3.05641327 -1.71560787 -1.52497848
 -2.68087602 -2.56362208 -0.65630354  0.80525034 -1.85046666 -0.28260537
 -1.48492354 -2.0119743  -1.49486286 -1.88809099 -1.26712887 -0.12376553
 -0.54335923 -0.93669295 -1.04386069 -1.33098784 -1.15069463 -1.61297443
 -1.83921831 -1.54373247 -1.67915196 -2.59192406 -2.70200289 -1.46070707
 -0.07701017 -2.82943326 -2.22903556 -0.70810668  1.33472069 -1.54636376
 -1.54502327 -2.14652175 -2.00497138 -1.2156697   0.65323956 -2.25878443
 -2.01964987 -2.06360698 -1.21190331 -1.97139254 -2.08860731 -1.67429017
 -1.47139701]
 P_stat:
 [3.73667757e-01 2.15976784e-01 3.07816730e-01 1.37914901e-01
 1.52341692e-01 1.06559474e-01 2.36771905e-01 6.29852276e-02
 4.82201120e-02 2.20583428e-02 2.91126420e-02 8.96907936e-02
 5.01510305e-02 1.77986662e-03 1.30851869e-04 2.42299679e-03
 8.70379681e-02 1.28092947e-01 7.69773998e-03 1.07891722e-02
 5.12009597e-01 4.21133713e-01 6.50653343e-02 7.77622711e-01
 1.38587875e-01 4.52009706e-02 1.35889990e-01 6.01874139e-02
 2.06144796e-01 9.01575680e-01 5.87252447e-01 3.49630240e-01
 2.97366509e-01 1.84261685e-01 2.50741031e-01 1.07925829e-01
 6.69163620e-02 1.23779322e-01 9.41179632e-02 1.00861806e-02
 7.31591385e-03 1.45047103e-01 9.38652381e-01 5.01038186e-03
 2.64895880e-02 4.79274266e-01 1.83016955e-01 1.22910517e-01
 1.23260651e-01 3.25725692e-02 4.58102454e-02 2.24819205e-01
 5.14057542e-01 2.48392718e-02 4.45569067e-02 4.02387196e-02
 2.26646371e-01 4.96138287e-02 3.77466924e-02 9.52543935e-02
 1.42294906e-01]
 Z_stat:
 [-0.89087872 -1.24008569 -1.02150847 -1.48808433 -1.43540933 -1.61922721
 -1.18570231 -1.86632461 -1.9848942  -2.30273753 -2.19329417 -1.70184522
 -1.96760191 -3.15524172 -3.87507898 -3.05641327 -1.71560787 -1.52497848
 -2.68087602 -2.56362208 -0.65630354  0.80525034 -1.85046666 -0.28260537
 -1.48492354 -2.0119743  -1.49486286 -1.88809099 -1.26712887 -0.12376553
 -0.54335923 -0.93669295 -1.04386069 -1.33098784 -1.15069463 -1.61297443
 -1.83921831 -1.54373247 -1.67915196 -2.59192406 -2.70200289 -1.46070707
 -0.07701017 -2.82943326 -2.22903556 -0.70810668  1.33472069 -1.54636376
 -1.54502327 -2.14652175 -2.00497138 -1.2156697   0.65323956 -2.25878443
 -2.01964987 -2.06360698 -1.21190331 -1.97139254 -2.08860731 -1.67429017
 -1.47139701]
 p_stat:
 [3.72994239e-01 2.14943700e-01 3.07013597e-01 1.36728656e-01
 1.51170490e-01 1.05398385e-01 2.35739881e-01 6.19959644e-02
 4.71562440e-02 2.12936150e-02 2.82861916e-02 8.87843877e-02
 4.91138600e-02 1.60365183e-03 1.06590122e-04 2.24002273e-03
 8.62338368e-02 1.27264464e-01 7.34297159e-03 1.03586265e-02
 5.11628839e-01 4.20675230e-01 6.42463193e-02 7.77479361e-01
 1.37564080e-01 4.42226461e-02 1.34950236e-01 5.90137359e-02
 2.05109216e-01 9.01500928e-01 5.86882488e-01 3.48916523e-01
 2.96549847e-01 1.83193013e-01 2.49857886e-01 1.06750063e-01
 6.58830820e-02 1.22653156e-01 9.31224324e-02 9.54408362e-03
 6.89231634e-03 1.44095847e-01 9.38615451e-01 4.66305244e-03
 2.58115385e-02 4.78879011e-01 1.81967779e-01 1.22016741e-01
 1.22340634e-01 3.18313755e-02 4.49661069e-02 2.24110771e-01
 5.13601851e-01 2.38967974e-02 4.34197182e-02 3.90549953e-02
 2.25549393e-01 4.86789940e-02 3.67430867e-02 9.40735864e-02
 1.41183782e-01]
Significance
No     41
Yes    20
Name: count, dtype: int64

Significant Channels:
['FC1', 'FC3', 'FC5', 'C1', 'C3', 'C5', 'CP3', 'CP5', 'P5', 'FC2', 'FC4', 'C2', 'C4', 'CP4', 'CP6', 'P2', 'P4', 'P6', 'POz', 'PO4']

In [26]:
df_alpha.to_excel('t-test_alpha.xlsx')
df_alpha

   Channel    T_Stat   P_Value Significance
0      Fp1 -0.890879  0.373668           No
1      AF3 -1.240086  0.215977           No
2      AF7 -1.021508  0.307817           No
3       Fz -1.488084  0.137915           No
4       F1 -1.435409  0.152342           No
..     ...       ...       ...          ...
56      P8 -1.211903  0.226646           No
57     POz -1.971393  0.049614          Yes
58     PO4 -2.088607  0.037747          Yes
59     PO8 -1.674290  0.095254           No
60      O2 -1.471397  0.142295           No

[61 rows x 4 columns]

In [27]:
t_stat_beta, p_beta_t = stats.ttest_ind(beta_power_SD, beta_power_NS, equal_var=False)
z_stat_beta, p_beta_z = ztest(beta_power_SD, beta_power_NS, value=0)
print("BETA: \n","T_stat:\n", t_stat_beta,"\n","P_stat:\n", p_beta_t,"\n Z_stat:\n", z_stat_beta,"\n p_stat:\n", p_beta_z)
# Create the DataFrame
df_beta = pd.DataFrame({
    'Channel': eeg_channels,
    'T_Stat': t_stat_beta,
    'P_Value': p_beta_t,
    'Significance': np.where(p_beta_t < 0.05, 'Yes', 'No') 
})
print(df_beta['Significance'].value_counts())

BETA:
 T_stat:
 [ 4.23921669  2.51761494  2.89461319  3.48788287  4.19638024  2.10685905
  3.6771072  -1.63800711  2.4346715   0.38439848  0.43718471 -0.75323952
  2.37234663  0.71981584 -1.29217127  0.55822172 -2.09657848  0.40343489
 -0.91181191  0.68379487  1.56652715 -1.07968836  0.03696587  1.78299044
  0.21006788  0.10425453 -0.39350503 -1.28567865  1.79269481  2.66962433
  0.80086037  2.69775989  2.9439016   1.84958624  0.01882383  3.86027683
  1.74907517  1.45323086 -0.15063213  2.88356939  2.07821513  1.20372793
  0.34844189  1.56011634  0.6259856   0.53534189  0.4331205  -0.10863737
  0.39695496 -0.39493032  0.03435887  0.61240489  0.64550503 -1.48317219
 -0.51081074  0.18449754  1.62409546  0.80921695 -1.0936407   1.94756246
  0.27309647]
 P_stat:
 [2.98602448e-05 1.24240455e-02 4.01084394e-03 5.41932115e-04
 3.39747349e-05 3.57260508e-02 2.76662603e-04 1.02214342e-01
 1.53424851e-02 7.00909085e-01 6.62216134e-01 4.51739368e-01
 1.81382014e-02 4.72041332e-01 1.97016838e-01 5.77011833e-01
 3.66929225e-02 6.86839972e-01 3.62394754e-01 4.94563692e-01
 1.18402191e-01 2.81003439e-01 9.70530494e-01 7.53245249e-02
 8.33731457e-01 9.17017367e-01 6.94155864e-01 1.99396829e-01
 7.40282237e-02 7.89138226e-03 4.23713479e-01 7.26679930e-03
 3.46770886e-03 6.52271502e-02 9.84990674e-01 1.36643118e-04
 8.10682505e-02 1.46914763e-01 8.80339657e-01 4.14483162e-03
 3.85022522e-02 2.29376117e-01 7.27686277e-01 1.19489635e-01
 5.31668640e-01 5.92698519e-01 6.65165452e-01 9.13544588e-01
 6.91613962e-01 6.93099609e-01 9.72607465e-01 5.40680244e-01
 5.19076156e-01 1.39152760e-01 6.09818970e-01 8.53728045e-01
 1.05303802e-01 4.18856762e-01 2.74828527e-01 5.26866751e-02
 7.84916816e-01]
 Z_stat:
 [ 4.23921669  2.51761494  2.89461319  3.48788287  4.19638024  2.10685905
  3.6771072  -1.63800711  2.4346715   0.38439848  0.43718471 -0.75323952
  2.37234663  0.71981584 -1.29217127  0.55822172 -2.09657848  0.40343489
 -0.91181191  0.68379487  1.56652715 -1.07968836  0.03696587  1.78299044
  0.21006788  0.10425453 -0.39350503 -1.28567865  1.79269481  2.66962433
  0.80086037  2.69775989  2.9439016   1.84958624  0.01882383  3.86027683
  1.74907517  1.45323086 -0.15063213  2.88356939  2.07821513  1.20372793
  0.34844189  1.56011634  0.6259856   0.53534189  0.4331205  -0.10863737
  0.39695496 -0.39493032  0.03435887  0.61240489  0.64550503 -1.48317219
 -0.51081074  0.18449754  1.62409546  0.80921695 -1.0936407   1.94756246
  0.27309647]
 p_stat:
 [2.24301067e-05 1.18152413e-02 3.79626014e-03 4.86861316e-04
 2.71214772e-05 3.51297989e-02 2.35893921e-04 1.01420210e-01
 1.49053147e-02 7.00683125e-01 6.61977397e-01 4.51305996e-01
 1.76754996e-02 4.71638390e-01 1.96297840e-01 5.76692989e-01
 3.60309062e-02 6.86628322e-01 3.61867740e-01 4.94104706e-01
 1.17225258e-01 2.80280978e-01 9.70512215e-01 7.45878593e-02
 8.33614698e-01 9.16967358e-01 6.93946510e-01 1.98555235e-01
 7.30217371e-02 7.59361537e-03 4.23212484e-01 6.98077706e-03
 3.24103031e-03 6.43732078e-02 9.84981643e-01 1.13258642e-04
 8.02780264e-02 1.46159667e-01 8.80265918e-01 3.93196008e-03
 3.76895493e-02 2.28694752e-01 7.27508350e-01 1.18732391e-01
 5.31324385e-01 5.92413465e-01 6.64927229e-01 9.13490117e-01
 6.91400672e-01 6.92894314e-01 9.72590982e-01 5.40269908e-01
 5.18599958e-01 1.38028668e-01 6.09483588e-01 8.53623160e-01
 1.04355437e-01 4.18390364e-01 2.74112593e-01 5.14673389e-02
 7.84779062e-01]
Significance
No     45
Yes    16
Name: count, dtype: int64

In [28]:
df_beta.to_excel('t-test_beta.xlsx')
df_beta

   Channel    T_Stat   P_Value Significance
0      Fp1  4.239217  0.000030          Yes
1      AF3  2.517615  0.012424          Yes
2      AF7  2.894613  0.004011          Yes
3       Fz  3.487883  0.000542          Yes
4       F1  4.196380  0.000034          Yes
..     ...       ...       ...          ...
56      P8  1.624095  0.105304           No
57     POz  0.809217  0.418857           No
58     PO4 -1.093641  0.274829           No
59     PO8  1.947562  0.052687           No
60      O2  0.273096  0.784917           No

[61 rows x 4 columns]

In [29]:
t_stat_gamma, p_gamma_t = stats.ttest_ind(gamma_power_SD, gamma_power_NS, equal_var=False)
z_stat_gamma, p_gamma_z = ztest(gamma_power_SD, gamma_power_NS, value=0)
print("GAMMA: \n","T_stat:\n", t_stat_gamma,"\n","P_stat:\n", p_gamma_t,"\n Z_stat:\n", z_stat_gamma,"\n p_stat:\n", p_gamma_z)
# Create the DataFrame
df_gamma = pd.DataFrame({
    'Channel': eeg_channels,
    'T_Stat': t_stat_gamma,
    'P_Value': p_beta_t,
    'Significance': np.where(p_gamma_t < 0.05, 'Yes', 'No') 
})
print(df_gamma['Significance'].value_counts())

GAMMA:
 T_stat:
 [ 3.61259616  2.50082125  2.86454504  2.14468345  3.37987414  1.26632739
  3.28344294 -1.50793035  0.38182753 -0.3629625   0.50684319 -0.58817908
  0.38040204 -0.68871509 -1.13787021  0.638672   -1.66624988 -0.11553473
 -0.79620987  0.29171264  1.97160353  0.00569144 -0.52311298  0.694154
 -0.3501263   0.54703573 -0.18820747 -1.13781103  1.78516385  2.18648556
  0.69962977  3.0580658   2.97910934  1.12452622 -0.30384768  3.56797712
  0.73682723  1.60793633 -0.81706975  2.16545243  1.40472528  0.31701325
 -0.7138247   1.5697116  -0.58409226 -0.16874543 -0.20608572 -1.29444322
 -0.77333442 -1.15566036 -0.42689489 -0.02730465 -0.24574671 -2.00681384
 -1.1325491   1.27875162  1.80110983  0.89103337 -1.61510414  1.75155368
 -0.26295061]
 P_stat:
 [3.61274844e-04 1.29462282e-02 4.39294600e-03 3.25544391e-02
 7.95879227e-04 2.06158012e-01 1.12184767e-03 1.32360777e-01
 7.02809854e-01 7.16892209e-01 6.12578691e-01 5.56730813e-01
 7.03867256e-01 4.91535391e-01 2.56010595e-01 5.23386130e-01
 9.64244737e-02 9.08090660e-01 4.26418326e-01 7.70655139e-01
 4.96759710e-02 9.95461629e-01 6.01278210e-01 4.87983432e-01
 7.26431379e-01 5.84704054e-01 8.50805912e-01 2.55889308e-01
 7.52099234e-02 2.93461087e-02 4.84593244e-01 2.37853436e-03
 3.09430182e-03 2.61454396e-01 7.61395748e-01 4.08902325e-04
 4.61664526e-01 1.08608065e-01 4.14423834e-01 3.09307157e-02
 1.60969276e-01 7.51446516e-01 4.75811062e-01 1.17245024e-01
 5.59532402e-01 8.66094007e-01 8.36825943e-01 1.96679891e-01
 4.40050729e-01 2.48758673e-01 6.69736608e-01 9.78230645e-01
 8.05999373e-01 4.58490754e-02 2.58236609e-01 2.01833966e-01
 7.28556262e-02 3.73424173e-01 1.07249321e-01 8.11474375e-02
 7.92722955e-01]
 Z_stat:
 [ 3.61259616  2.50082125  2.86454504  2.14468345  3.37987414  1.26632739
  3.28344294 -1.50793035  0.38182753 -0.3629625   0.50684319 -0.58817908
  0.38040204 -0.68871509 -1.13787021  0.638672   -1.66624988 -0.11553473
 -0.79620987  0.29171264  1.97160353  0.00569144 -0.52311298  0.694154
 -0.3501263   0.54703573 -0.18820747 -1.13781103  1.78516385  2.18648556
  0.69962977  3.0580658   2.97910934  1.12452622 -0.30384768  3.56797712
  0.73682723  1.60793633 -0.81706975  2.16545243  1.40472528  0.31701325
 -0.7138247   1.5697116  -0.58409226 -0.16874543 -0.20608572 -1.29444322
 -0.77333442 -1.15566036 -0.42689489 -0.02730465 -0.24574671 -2.00681384
 -1.1325491   1.27875162  1.80110983  0.89103337 -1.61510414  1.75155368
 -0.26295061]
 p_stat:
 [3.03146631e-04 1.23905698e-02 4.17608760e-03 3.19781653e-02
 7.25190313e-04 2.05395895e-01 1.02547403e-03 1.31572354e-01
 7.02589300e-01 7.16632894e-01 6.12264849e-01 5.56412099e-01
 7.03647002e-01 4.91002576e-01 2.55174682e-01 5.23036330e-01
 9.56636544e-02 9.08021297e-01 4.25910063e-01 7.70506344e-01
 4.86548842e-02 9.95458910e-01 6.00895632e-01 4.87585634e-01
 7.26243917e-01 5.84354183e-01 8.50714016e-01 2.55199399e-01
 7.42347441e-02 2.87800999e-02 4.84158549e-01 2.22770657e-03
 2.89087600e-03 2.60789852e-01 7.61243943e-01 3.59747910e-04
 4.61227422e-01 1.07849123e-01 4.13888568e-01 3.03530544e-02
 1.60102986e-01 7.51233547e-01 4.75335582e-01 1.16482220e-01
 5.59158241e-01 8.65996885e-01 8.36723950e-01 1.95512372e-01
 4.39324492e-01 2.47820109e-01 6.69455887e-01 9.78216751e-01
 8.05878311e-01 4.47694887e-02 2.57403654e-01 2.00984535e-01
 7.16855699e-02 3.72911269e-01 1.06288144e-01 7.98505838e-02
 7.92588651e-01]
Significance
No     48
Yes    13
Name: count, dtype: int64

In [30]:
df_gamma.to_excel('t-test_gamma.xlsx')
df_gamma

   Channel    T_Stat   P_Value Significance
0      Fp1  3.612596  0.000030          Yes
1      AF3  2.500821  0.012424          Yes
2      AF7  2.864545  0.004011          Yes
3       Fz  2.144683  0.000542          Yes
4       F1  3.379874  0.000034          Yes
..     ...       ...       ...          ...
56      P8  1.801110  0.105304           No
57     POz  0.891033  0.418857           No
58     PO4 -1.615104  0.274829           No
59     PO8  1.751554  0.052687           No
60      O2 -0.262951  0.784917           No

[61 rows x 4 columns]